/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.GedungController;
import Controller.PeminjamanController;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import java.util.*;


/**
 *
 * @author Novi
 */
public class MenuMahasiswa extends javax.swing.JFrame {
    GedungController gedungController = new GedungController();
    
    private String idUser;
    private int idPeminjaman;

    /**
     * Creates new form Home
     */
    public MenuMahasiswa() {
        initComponents();
        
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
       
        showPeminjamanData(idUser);
        gedungController.setJComboBoxModel(jComboBoxCariGedung);
        
    }
    
    public String getidUser(String idUser){
        return this.idUser = idUser;
    }
    
    public final void showPeminjamanData(String idUser) {
        DefaultTableModel tableModel = (DefaultTableModel) TabelPeminjaman.getModel();
        tableModel.setRowCount(0);
        PeminjamanController.showPeminjamanMahasiswa(tableModel, idUser);
    }
     
    public void showHistoryPeminjamanMahasiswa(String idUser) {
        DefaultTableModel tableModel = (DefaultTableModel) TabelHistory.getModel();
        tableModel.setRowCount(0);
        PeminjamanController.showHistoryMahasiswa(tableModel, idUser);
    }
    
    public void displayMahasiswaProfile(String idUser, String userNama, String userProgramStudi,String userFakultas, String userNoTelepon) {
        NamaUser.setText(userNama);
        jLabelNIM.setText(idUser);
        jLabelNama.setText(userNama);
        jLabelProgramStudi.setText(userProgramStudi);
        jLabelFakultas.setText(userFakultas);
        jLabelNoTelepon5.setText(userNoTelepon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        allMenu = new javax.swing.JPanel();
        HomePanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        NIP = new javax.swing.JLabel();
        NoTelepon = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        jLabelNama = new javax.swing.JLabel();
        Jabatan = new javax.swing.JLabel();
        jLabelProgramStudi = new javax.swing.JLabel();
        jLabelFakultas = new javax.swing.JLabel();
        jLabelNIM = new javax.swing.JLabel();
        jLabelNoTelepon1 = new javax.swing.JLabel();
        jLabelNoTelepon2 = new javax.swing.JLabel();
        jLabelNoTelepon3 = new javax.swing.JLabel();
        jLabelNoTelepon4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        NoTelepon1 = new javax.swing.JLabel();
        jLabelNoTelepon5 = new javax.swing.JLabel();
        jLabelNoTelepon8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDateTAwal = new com.toedter.calendar.JDateChooser();
        jComboBoxCariGedung = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHasilCari = new javax.swing.JTable();
        jButtonCari = new javax.swing.JButton();
        PeminjamanPanel = new javax.swing.JPanel();
        jButtonBatal = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jDateTanggalPeminjaman = new com.toedter.calendar.JDateChooser();
        jDateTanggalSelesai = new com.toedter.calendar.JDateChooser();
        jComboBoxGedung = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        TabelPeminjaman = new javax.swing.JTable();
        jComboBoxKegiatan = new javax.swing.JComboBox<>();
        HistoryPeminjaman = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TabelHistory = new javax.swing.JTable();
        sidepanel = new javax.swing.JPanel();
        NamaUser = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        menuPeminjaman = new javax.swing.JButton();
        menuHistory = new javax.swing.JButton();
        menuHome = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(23, 107, 135));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 100));

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Sistem Informasi Peminjaman Gedung");

        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel9))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        allMenu.setMinimumSize(new java.awt.Dimension(800, 500));
        allMenu.setPreferredSize(new java.awt.Dimension(800, 500));
        allMenu.setLayout(new java.awt.CardLayout());

        HomePanel.setBackground(new java.awt.Color(255, 255, 255));
        HomePanel.setPreferredSize(new java.awt.Dimension(900, 477));
        HomePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setForeground(new java.awt.Color(0, 51, 51));

        NIP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NIP.setText("NIM");

        NoTelepon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NoTelepon.setText("Fakultas");

        Nama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Nama.setText("Nama");

        jLabelNama.setAutoscrolls(true);
        jLabelNama.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabelNamaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jLabelNamaAncestorRemoved(evt);
            }
        });

        Jabatan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Jabatan.setText("Program Studi");

        jLabelProgramStudi.setAutoscrolls(true);

        jLabelFakultas.setAutoscrolls(true);

        jLabelNIM.setAutoscrolls(true);
        jLabelNIM.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabelNIMAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jLabelNIMAncestorRemoved(evt);
            }
        });

        jLabelNoTelepon1.setText(": ");
        jLabelNoTelepon1.setAutoscrolls(true);

        jLabelNoTelepon2.setText(": ");
        jLabelNoTelepon2.setAutoscrolls(true);

        jLabelNoTelepon3.setText(": ");
        jLabelNoTelepon3.setAutoscrolls(true);

        jLabelNoTelepon4.setText(": ");
        jLabelNoTelepon4.setAutoscrolls(true);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user_6994648.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("PROFIL MAHASISWA");

        NoTelepon1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NoTelepon1.setText("No Telepon");

        jLabelNoTelepon5.setAutoscrolls(true);

        jLabelNoTelepon8.setText(": ");
        jLabelNoTelepon8.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 57, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NIP)
                            .addComponent(Jabatan)
                            .addComponent(NoTelepon)
                            .addComponent(Nama)
                            .addComponent(NoTelepon1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(11, 11, 11)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel7))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabelNoTelepon4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelProgramStudi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabelNoTelepon2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabelNoTelepon1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelNoTelepon3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNoTelepon8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNoTelepon5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelFakultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(53, 53, 53))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel7)))
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNIM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NIP, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNoTelepon1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Nama, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addComponent(jLabelNoTelepon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelProgramStudi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Jabatan, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addComponent(jLabelNoTelepon4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelFakultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NoTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNoTelepon3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NoTelepon1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelNoTelepon8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelNoTelepon5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        HomePanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 410, 360));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("SISTEM INFORMASI JADWAL GEDUNG");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("UNIVERSITAS MULAWARMAN");

        jDateTAwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateTAwalMouseClicked(evt);
            }
        });

        jComboBoxCariGedung.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCariGedung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCariGedungActionPerformed(evt);
            }
        });

        jTableHasilCari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableHasilCari.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Gedung", "Tanggal Awal", "Tanggal Akhir", "Kegiatan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableHasilCari.setEnabled(false);
        jTableHasilCari.setShowGrid(true);
        jTableHasilCari.getTableHeader().setResizingAllowed(false);
        jTableHasilCari.getTableHeader().setReorderingAllowed(false);
        jTableHasilCari.setUpdateSelectionOnSort(false);
        jTableHasilCari.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(jTableHasilCari);

        jButtonCari.setText("Cek Jadwal");
        jButtonCari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButtonCariFocusGained(evt);
            }
        });
        jButtonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateTAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxCariGedung, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonCari))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel4)))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(58, 58, 58))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jDateTAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxCariGedung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonCari, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        HomePanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 450, 360));

        allMenu.add(HomePanel, "card4");

        PeminjamanPanel.setBackground(new java.awt.Color(255, 255, 255));
        PeminjamanPanel.setMaximumSize(new java.awt.Dimension(1000, 600));
        PeminjamanPanel.setMinimumSize(new java.awt.Dimension(1000, 600));
        PeminjamanPanel.setPreferredSize(new java.awt.Dimension(1000, 600));

        jButtonBatal.setText("Batal");
        jButtonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBatalActionPerformed(evt);
            }
        });

        jLabel22.setText("Gedung");

        jButtonAdd.setText("Tambah");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jLabel23.setText("Tanggal Peminjaman");

        jLabel24.setText("Tanggal Selesai");

        jLabel25.setText("Keperluan");

        jDateTanggalSelesai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateTanggalSelesaiMouseClicked(evt);
            }
        });

        jComboBoxGedung.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxGedung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGedungActionPerformed(evt);
            }
        });

        TabelPeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Peminjaman", "NIM", "Gedung", "Tanggal Peminjaman", "Tanggal Selesai", "Keperluan", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelPeminjaman.getTableHeader().setResizingAllowed(false);
        TabelPeminjaman.getTableHeader().setReorderingAllowed(false);
        TabelPeminjaman.setUpdateSelectionOnSort(false);
        TabelPeminjaman.setVerifyInputWhenFocusTarget(false);
        TabelPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelPeminjamanMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(TabelPeminjaman);

        jComboBoxKegiatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seminar", "Lomba", "Rapat", "Kuliah Umum" }));

        javax.swing.GroupLayout PeminjamanPanelLayout = new javax.swing.GroupLayout(PeminjamanPanel);
        PeminjamanPanel.setLayout(PeminjamanPanelLayout);
        PeminjamanPanelLayout.setHorizontalGroup(
            PeminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeminjamanPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(PeminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PeminjamanPanelLayout.createSequentialGroup()
                        .addGroup(PeminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel22))
                        .addGap(103, 103, 103)
                        .addGroup(PeminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxKegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxGedung, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PeminjamanPanelLayout.createSequentialGroup()
                        .addGroup(PeminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addGap(45, 45, 45)
                        .addGroup(PeminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateTanggalSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateTanggalPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PeminjamanPanelLayout.createSequentialGroup()
                        .addComponent(jButtonAdd)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBatal)))
                .addGap(0, 612, Short.MAX_VALUE))
            .addGroup(PeminjamanPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PeminjamanPanelLayout.setVerticalGroup(
            PeminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeminjamanPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(PeminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jComboBoxGedung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PeminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jComboBoxKegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PeminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateTanggalPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(PeminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateTanggalSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(30, 30, 30)
                .addGroup(PeminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBatal)
                    .addComponent(jButtonAdd))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 117, Short.MAX_VALUE))
        );

        allMenu.add(PeminjamanPanel, "card3");

        HistoryPeminjaman.setBackground(new java.awt.Color(255, 255, 255));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        TabelHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Peminjaman", "NIM", "Nama Gedung", "Tanggal Peminjaman", "Tanggal Selesai", "Keperluan", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelHistory.setEnabled(false);
        TabelHistory.setShowGrid(true);
        TabelHistory.getTableHeader().setResizingAllowed(false);
        TabelHistory.getTableHeader().setReorderingAllowed(false);
        TabelHistory.setUpdateSelectionOnSort(false);
        TabelHistory.setVerifyInputWhenFocusTarget(false);
        jScrollPane6.setViewportView(TabelHistory);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 419, Short.MAX_VALUE)
                    .addComponent(jLabel39)
                    .addGap(0, 419, Short.MAX_VALUE)))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 419, Short.MAX_VALUE)
                    .addComponent(jLabel40)
                    .addGap(0, 419, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 240, Short.MAX_VALUE)
                    .addComponent(jLabel39)
                    .addGap(0, 240, Short.MAX_VALUE)))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 240, Short.MAX_VALUE)
                    .addComponent(jLabel40)
                    .addGap(0, 240, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout HistoryPeminjamanLayout = new javax.swing.GroupLayout(HistoryPeminjaman);
        HistoryPeminjaman.setLayout(HistoryPeminjamanLayout);
        HistoryPeminjamanLayout.setHorizontalGroup(
            HistoryPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HistoryPeminjamanLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        HistoryPeminjamanLayout.setVerticalGroup(
            HistoryPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        allMenu.add(HistoryPeminjaman, "card4");

        sidepanel.setBackground(new java.awt.Color(11, 36, 71));
        sidepanel.setForeground(new java.awt.Color(255, 255, 255));
        sidepanel.setPreferredSize(new java.awt.Dimension(200, 600));

        NamaUser.setForeground(new java.awt.Color(255, 255, 255));
        NamaUser.setText("Nama Mahasiswa");

        jLabel10.setForeground(new java.awt.Color(102, 204, 255));
        jLabel10.setText("Mahasiswa");

        menuPeminjaman.setText("Peminjaman");
        menuPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPeminjamanActionPerformed(evt);
            }
        });

        menuHistory.setText("History");
        menuHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHistoryActionPerformed(evt);
            }
        });

        menuHome.setText("Home");
        menuHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHomeActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user_6994648.png"))); // NOI18N

        javax.swing.GroupLayout sidepanelLayout = new javax.swing.GroupLayout(sidepanel);
        sidepanel.setLayout(sidepanelLayout);
        sidepanelLayout.setHorizontalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NamaUser)
                    .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(menuHome, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(menuPeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(menuHistory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(sidepanelLayout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(sidepanelLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel10))))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        sidepanelLayout.setVerticalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepanelLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(NamaUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(33, 33, 33)
                .addComponent(menuHome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(menuPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(menuHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
                    .addComponent(allMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(allMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 494, Short.MAX_VALUE))
                    .addComponent(sidepanel, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login login = new Login();
        
        this.dispose();
        login.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void menuPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPeminjamanActionPerformed
        allMenu.removeAll();
        allMenu.repaint();
        allMenu.revalidate();

        allMenu.add(PeminjamanPanel);
        allMenu.repaint();
        allMenu.revalidate();

        gedungController.setJComboBoxModel(jComboBoxGedung);
    }//GEN-LAST:event_menuPeminjamanActionPerformed

    private void menuHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHistoryActionPerformed
        allMenu.removeAll();
        allMenu.repaint();
        allMenu.revalidate();

        allMenu.add(HistoryPeminjaman);
        allMenu.repaint();
        allMenu.revalidate();

        showHistoryPeminjamanMahasiswa(idUser);
    }//GEN-LAST:event_menuHistoryActionPerformed

    private void menuHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHomeActionPerformed
        allMenu.removeAll();
        allMenu.repaint();
        allMenu.revalidate();

        allMenu.add(HomePanel);
        allMenu.repaint();
        allMenu.revalidate();
    }//GEN-LAST:event_menuHomeActionPerformed

    private void jLabelNamaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabelNamaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelNamaAncestorAdded

    private void jLabelNamaAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabelNamaAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelNamaAncestorRemoved

    private void jLabelNIMAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabelNIMAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelNIMAncestorAdded

    private void jLabelNIMAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabelNIMAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelNIMAncestorRemoved

    private void jDateTAwalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateTAwalMouseClicked

    }//GEN-LAST:event_jDateTAwalMouseClicked

    private void jComboBoxCariGedungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCariGedungActionPerformed

    String selectedGedung = (String) jComboBoxCariGedung.getSelectedItem();

    // Perform some action based on the selected item
    if (selectedGedung != null) {
        // Add your logic here, for example:
        System.out.println("Selected Gedung: " + selectedGedung);
    }

    }//GEN-LAST:event_jComboBoxCariGedungActionPerformed

    private void jButtonCariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonCariFocusGained

    }//GEN-LAST:event_jButtonCariFocusGained

    private void jButtonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCariActionPerformed

        int idGedung = gedungController.getSelectedGedungId();
        Date tanggalPeminjaman = jDateTAwal.getDate();

        DefaultTableModel tableModel = gedungController.cariGedung(idGedung, tanggalPeminjaman);
        jTableHasilCari.setModel(tableModel);

    }//GEN-LAST:event_jButtonCariActionPerformed

    private void TabelPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelPeminjamanMouseClicked
        jButtonAdd.setEnabled(false);

        DefaultTableModel tblModel = (DefaultTableModel)TabelPeminjaman.getModel();
        int idPeminjaman1 = (int) tblModel.getValueAt(TabelPeminjaman.getSelectedRow(), 0);
        this.idPeminjaman = idPeminjaman1;

        System.out.println(idPeminjaman);
        String tabelNIM = tblModel.getValueAt(TabelPeminjaman.getSelectedRow(), 1).toString();
        String tabelGedung = tblModel.getValueAt(TabelPeminjaman.getSelectedRow(), 2).toString();
        Date tabelTanggalP = (Date) tblModel.getValueAt(TabelPeminjaman.getSelectedRow(), 3);
        Date tabelTanggalS = (Date) tblModel.getValueAt(TabelPeminjaman.getSelectedRow(), 4);
        String tabelKeperluan = tblModel.getValueAt(TabelPeminjaman.getSelectedRow(), 5).toString();
        String tabelStatus = tblModel.getValueAt(TabelPeminjaman.getSelectedRow(), 6).toString();

        jComboBoxGedung.setSelectedItem(tabelGedung);
        jDateTanggalPeminjaman.setDate(tabelTanggalP);
        jDateTanggalSelesai.setDate(tabelTanggalS);
        jComboBoxKegiatan.setSelectedItem(tabelKeperluan);

        jComboBoxGedung.setEnabled(false);
        jDateTanggalPeminjaman.setEnabled(false);
        jDateTanggalSelesai.setEnabled(false);
        jComboBoxKegiatan.setEnabled(false);
    }//GEN-LAST:event_TabelPeminjamanMouseClicked

    private void jComboBoxGedungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGedungActionPerformed

    }//GEN-LAST:event_jComboBoxGedungActionPerformed

    private void jDateTanggalSelesaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateTanggalSelesaiMouseClicked
        jDateTanggalSelesai.setEnabled(false);
    }//GEN-LAST:event_jDateTanggalSelesaiMouseClicked

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed

        try {
            String idUserMahasiswa = idUser;
            Date tanggalPeminjaman = jDateTanggalPeminjaman.getDate();
            Date tanggalSelesai = jDateTanggalSelesai.getDate();
            String keperluan = jComboBoxKegiatan.getSelectedItem().toString();
            String status = "Pending";
            int gedungId = gedungController.getSelectedGedungId();
            String staffId = "12345";
            java.sql.Date sqlDatePeminjaman = new java.sql.Date(tanggalPeminjaman.getTime());
            java.sql.Date sqlDateSelesai = new java.sql.Date(tanggalSelesai.getTime());
            PeminjamanController.addPeminjaman(sqlDatePeminjaman, sqlDateSelesai, keperluan, status, gedungId, idUserMahasiswa, staffId);

            showPeminjamanData(idUser);

        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatalActionPerformed

        jComboBoxGedung.setSelectedIndex(0);
        jDateTanggalPeminjaman.setDate(null);
        jDateTanggalSelesai.setDate(null);
        jComboBoxKegiatan.setSelectedIndex(0);

        jButtonAdd.setEnabled(true);
        jComboBoxGedung.setEnabled(true);
        jDateTanggalPeminjaman.setEnabled(true);
        jDateTanggalSelesai.setEnabled(true);
        jComboBoxKegiatan.setEnabled(true);
    }//GEN-LAST:event_jButtonBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        FlatLightLaf.setup();
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MenuStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MenuStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MenuStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MenuStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MenuMahasiswa().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HistoryPeminjaman;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JLabel Jabatan;
    private javax.swing.JLabel NIP;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel NamaUser;
    private javax.swing.JLabel NoTelepon;
    private javax.swing.JLabel NoTelepon1;
    private javax.swing.JPanel PeminjamanPanel;
    private javax.swing.JTable TabelHistory;
    private javax.swing.JTable TabelPeminjaman;
    private javax.swing.JPanel allMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonBatal;
    private javax.swing.JButton jButtonCari;
    private javax.swing.JComboBox<String> jComboBoxCariGedung;
    private javax.swing.JComboBox<String> jComboBoxGedung;
    private javax.swing.JComboBox<String> jComboBoxKegiatan;
    private com.toedter.calendar.JDateChooser jDateTAwal;
    private com.toedter.calendar.JDateChooser jDateTanggalPeminjaman;
    private com.toedter.calendar.JDateChooser jDateTanggalSelesai;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFakultas;
    private javax.swing.JLabel jLabelNIM;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelNoTelepon1;
    private javax.swing.JLabel jLabelNoTelepon2;
    private javax.swing.JLabel jLabelNoTelepon3;
    private javax.swing.JLabel jLabelNoTelepon4;
    private javax.swing.JLabel jLabelNoTelepon5;
    private javax.swing.JLabel jLabelNoTelepon8;
    private javax.swing.JLabel jLabelProgramStudi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTableHasilCari;
    private javax.swing.JButton menuHistory;
    private javax.swing.JButton menuHome;
    private javax.swing.JButton menuPeminjaman;
    private javax.swing.JPanel sidepanel;
    // End of variables declaration//GEN-END:variables
}
